---
title: "hw1"
output: html_document
---
#Работа с данными.
#Загрузите данные в датафрейм, который назовите data.df.
data.df <- read.table("http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat")
#Сколько строк и столбцов в data.df? Если получилось не 5070 наблюдений 27 переменных, то проверяйте аргументы.

nrow(data.df)
ncol(data.df)

#Получите имена колонок из data.df.

colnames(data.df)

#Найдите значение из 5 строки седьмого столбца.

data.df[5,7]

#Напечатайте целиком 2 строку из data.df

data.df[2,]

#Объясните, что делает следующая строка кода 

names(data.df) <- c("year", "month", "day", seq(0,23))

#Устанавливает названия столбцам датафрейма

#Воспользуйтесь функциями head и tail, чтобы просмотреть таблицу. Что представляют собой последние 24 колонки?

head(data.df)
tail(data.df)

#Колонки, состоящие из нулей (осадков не было с 25 по 30 ноября 80-го года)

#Добавьте новую колонку с названием daily, в которую запишите сумму крайних правых 24 колонок. Постройте гистограмму по этой колонке. Какие выводы можно сделать?

last.column.index <- length(colnames(data.df))
start.sum.column <- last.column.index - 23
data.df["daily"] <- rowSums(data.df[start.sum.column:start.sum.column])
hist(data.df$daily)
#Значения отрицательные

#Создайте новый датафрейм fixed.df в котром исправьте замеченную ошибку. Постройте новую гистограмму, поясните почему она более корректна.
fixed.df <- data.df
fixed.df$daily <- abs(fixed.df$daily)
hist(fixed.df$daily)
#Данная гистограма более предпочтительная, т.к. используем модуль и можно избавиться от отрицательных значений.

#Синтаксис и типизирование

#Для каждой строки кода поясните полученный результат, либо объясните почему она ошибочна.
v <- c("4", "8", "15", "16", "23", "42") 
#необходимо убрать кавычки
max(v) 
#неверно исходя из написанного выше
sort(v)
#сортировка как-то сортирует
sum(v)
#неверно, необходимо складывать не символы,а конкретные значения (передается неверный тип данных)

#
# Для следующих наборов команд поясните полученный результат, либо объясните почему они ошибочна.
v2 <- c("5",7,12)
v2[2] + 2[3]
#Нельзя складывать числовой тип данных и текстовый
df3 <- data.frame(z1="5",z2=7,z3=12)
df3[1,2] + df3[1,3]
#Аналогично выше
l4 <- list(z1="6", z2=42, z3="49", z4=126)
l4[[2]] + l4[[4]]
#Работает только потому что складывает 2 и 4 значения (числовые типы данных)
l4[2] + l4[4]
#Ошибка при сложении типа данных list [[]]

#Работа с функциями и операторами
Оператор двоеточие создаёт последовательность целых чисел по порядку. Этот оператор — частный случай функции seq(), которую вы использовали раньше. Изучите эту #функцию, вызвав команду ?seq. Испольуя полученные знания выведите на экран:

#Числа от 1 до 10000 с инкрементом 372.
seq(1, 10000, by = 372)

#Числа от 1 до 10000 длиной 50.
seq(1, 10000, length.out = 50)

#Функция rep() повторяет переданный вектор указанное число раз. Объясните разницу между rep(1:5,times=3) и rep(1:5, each=3).
rep(1:5,times=3)
rep(1:5, each=3)

#times=3 выводит массив три раза, each же выводит каждый элемент по 3 раза
