---
title: "hw2"
author: "Марчук Александр"
date: '10 октября 2018 г '
output: html_document
---
#Загрузите данные в датафрейм, который назовите data.
data<-data.frame(read.csv("https://raw.githubusercontent.com/SergeyMirvoda/MD-DA-2018/master/data/calif_penn_2011.csv"))
data
#Сколько строк и столбцов в data?
nrow(data)
ncol(data)
# 11275 строк 34 столбца
#Выполните следующую команду и объясните, что она делает. colSums(apply(data,c(1,2), is.na))
colSums(apply(data,c(1,2), is.na))
#Команада сумирует неполные данные (с отсутствующим значением - na)
#Функция na.omit() принимает датафрейм и возвращает новый датафрейм, игнорируя строки, содержащие значение NA. 

OriginalData<-nrow(data)
data<-na.omit(data)

#Сколько строк было удалено?

OriginalData-nrow(data)
#Было удалено 670 строк

#Соответствует ли результат выполнения, значениям из пункта 3?

#Не соответсвует. colSums(apply... считает каждый элемент массива со значением na по столбцам, а na.omit, если вся строка является пустой. 

#Новые дома
#Переменная(колонка) Built_2005_or_later содержит данные о проценте домов, построенных с 2005 года. Постройте диаграмму рассеяния (scatterplot) медианы стоимости #домов (переменная Median_house_value) относительно процента новых домов.

scatter.smooth(data$Built_2005_or_later, data$Median_house_value)

#Постройте ещё два графика для каждого из штатов отдельно. Номер штата содержится в переменной (STATEFP), где Калифорния 6-й штат, а Пенсильвания 42.
scatter.smooth(data$Built_2005_or_later[data$STATEFP==6], data$Median_house_value[data$STATEFP==6])
scatter.smooth(data$Built_2005_or_later[data$STATEFP==42], data$Median_house_value[data$STATEFP==42])

#Незанятые дома
#Уровень найма (vacancy rate) — доля домов, которые не были заняты. В данных содержатся колонки, содержащие общее количество домовладений и количество не занятых #домовладений.
#В датафрейм data добавьте новую колонку vacancy_rate, которая должна содержать вышеописанный показатель.

data$vacancy_rate<-data$Vacant_units / data$Total_units

#Найдите минимум, максимум, среднее и медиану полученных значений показателя.

min(data$vacancy_rate)
max(data$vacancy_rate)
mean(data$vacancy_rate)
median(data$vacancy_rate)

#Постройте диаграмму уровня найма относительно медианы стоимости домов. Что можно заметить?

plot(data$Median_house_value, data$vacancy_rate)

#чем выше медиана стоимости тем меньше уровень найма - дешевые дома популярнее дорогих

#Корреляция
#Колонка COUNTYFP содержит числовой код округа внутри штата. Нас интересуют Butte County (округ 7 в Калифорнии), Santa Clara (округ 85 в Калифорнии) и York County #(округ 133 в Пенсильвании).
#Объясните, что делает приведённый в конце задания код и как именно он это делает.
#добавление в вектор(acc) номеров строк, которые относятся к штату 6(Калифорния) и городу с индексом 1
#сохранение в вектор accmv медианы стоимости домов, нахождение медианы

#Напишите другим способом в одну строку, то же самое, что делает нижеуказанный код. Способов получить тот же ответ множество, достаточно одного.

median(data.fixed$Median_house_value[data.fixed$STATEFP == 6][data.fixed$COUNTYFP == 1], na.rm = TRUE)

#Найдите средний процент построенных домовладений в округах (Butte County, Santa Clara, York County)
California <- data$STATEFP == 6
totalHousesCalifornia <- sum(data$Total_units[California])
ButteCounty <- data$COUNTYFP == 7
mean(data$Total_units[California & ButteCounty]/totalHousesCalifornia, na.rm = TRUE)
SantaClara <- data$COUNTYFP == 85
mean(data$Total_units[California & SantaClara]/totalHousesCalifornia, na.rm = TRUE)
Pensy <- data$STATEFP == 42
totalHousesPensy <- sum(data$Total_units[Pensy])
YorkCounty <- data$COUNTYFP == 133
mean(data$Total_units[Pensy & YorkCounty]/totalHousesPensy, na.rm = TRUE)

#Функция cor рассчитывает коэффициент корреляции между двумя переменными. Рассчитайте корреляцию между медианы стоимости домовладений (Median_house_value) и #процентом построенных домов (Built_2005_or_later):
#для всего набора данных
cor(as.numeric(data$Built_2005_or_later), data$Median_house_value)
#для Калифорнии
cor(as.numeric(data$Built_2005_or_later[California]), data$Median_house_value[California])
#для Пенсильвании
cor(as.numeric(data$Built_2005_or_later[Pensy]), data$Median_house_value[Pensy])
#для округа Butte County
cor(as.numeric(data$Built_2005_or_later[California & ButteCounty]), data$Median_house_value[California & ButteCounty],use = "pairwise.complete.obs")
#для округа Santa Clara
cor(as.numeric(data$Built_2005_or_later[California & SantaClara]), data$Median_house_value[California & SantaClara],use = "pairwise.complete.obs")
#для округа York County
cor(as.numeric(data$Built_2005_or_later[Pensy & YorkCounty]), data$Median_house_value[Pensy & YorkCounty],use = "pairwise.complete.obs")

#Постройте три диаграммы медианы стоимости домовладений (Median_house_value) относительно медианы дохода (Median_household_income) для трёх округов. Допустимо #указать все три на одном графике.

plot(data$Median_house_value[California & ButteCounty] ~ data$Median_household_income[California & ButteCounty])
plot(data$Median_house_value[California & SantaClara] ~ data$Median_household_income[California & SantaClara])
plot(data$Median_house_value[Pensy & YorkCounty] ~ data$Median_household_income[Pensy & YorkCounty])
